#Project Setup
general:
  productiveBranch: 'master'
  

#Steps Specific Configuration
steps:

   
  mavenExecute:
#    dockerImage: 'maven:3.5.0-jdk-8'
    projectSettingsFile : ''

  deployToCfWithCli:
#    dockerImage: 's4sdk/docker-cf-cli'
    smokeTestStatusCode: '200'


#Stage Specific Configurations
stages:
  
    
 
  mavenExecuteStaticCodeChecks:
    spotBugsExcludeFilterFile: '' #Path to findbugs exclude file
    pmdMaxAllowedViolations: '' # List or ANT style patterns

 # backendIntegrationTests:
   # credentials:
    #  - alias: 'MOCK_SYSTEM'
    #    credentialId: 'MOCK_SYSTEM'

  s4SdkQualityChecks:
    jacocoExcludes:
      - '**/com/sap/cloud/s4hana/examples/addressmgr/config/*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/datasource/*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/models/*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/util/TenantUtil.*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/LocalAddressServlet.*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/TenantProvisioningServlet.*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/views/ViewModelConverter.*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/views/AddressView.*'
      - '**/com/sap/cloud/s4hana/examples/addressmgr/commands/GetSingleBusinessPartnerByIdCommand.*'
#    nonErpDestinations:
#      - ''

  productionDeployment:
    cfTargets:
      - org: 'P1942815479trial_trial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'address-manager'
        manifest: 'manifest.yml'
        credentialsId: 'github'

